apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-resolved.yaml convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: trino-coordinator
  name: trino-coordinator
  namespace: default
spec:
  ports:
    - port: 8080
  selector:
    io.kompose.service: trino-coordinator
status:
  loadBalancer: {}
