FROM ubuntu:20.04

COPY ./conf/focal-sources.list /etc/apt/sources.list

# Install basic packages
RUN apt update && apt-get update
RUN apt clean && apt-get clean 
RUN apt-get upgrade -y
RUN apt-get install -y net-tools vim curl wget unzip iputils-ping
RUN apt-get install -y procps ssh sudo
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y libk5crypto3 libkrb5-3 libsqlite3-0
RUN apt-get install -y openjdk-8-jdk libpostgresql-jdbc-java && \
  ln -sf /usr/bin/python3 /usr/bin/python && \
  rm -rf /var/lib/apt/lists/*
RUN pip3 install wget requests datawrangler

