FROM ubuntu:22.04

COPY ./conf/jammy-sources.list /etc/apt/sources.list

# Install basic packages
RUN apt update && apt-get update
RUN apt clean && apt-get clean 
RUN apt-get upgrade -y
RUN apt-get install -y net-tools vim curl wget unzip iputils-ping
RUN apt-get install -y procps ssh sudo
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y libk5crypto3 libkrb5-3 libsqlite3-0
RUN apt install -y openjdk-17-jdk 
RUN apt install -y libpostgresql-jdbc-java
RUN ln -sf /usr/bin/python3 /usr/bin/python && rm -rf /var/lib/apt/lists/*
RUN pip3 install wget requests datawrangler

